dist: trusty
sudo: false

addons:
  apt:
    packages:
      - texlive-latex-extra

before_script: chmod +x build.sh
script:        ./build.sh

deploy:
  provider:     releases
  skip_cleanup: true
  file:         _build/*.pdf
  api_key:
    secure: CuhCg5pHiTXNYxEhB7P/0YK3RuS6eyB6uFElzeHgxs1/IHYKYa+RIyoauqITbXOsr8S1qKkiS6a2hwoAQwoD1hmg78UlJ2Q56Iy0At8wyGy6vMl5tpEc2kLj8/leyp91HZmmSDNS8iDt8f0Emg8pQRRBRuThjIJMh3nq65FzEdYHcSvAwmyRXczz7/WrjGUNHnl4jA5CI6qgLgjcy/XbMLR8fJ8+i3cTEyYRRU7z/xTCjTPTh4uet7l/Yn+vrRko4lwmTv5BJyboN49kvw+U7PTenomMRWh+/w+AkjhbFtRw8bySToulJkCPt3roqtY/6zFnY1QmtPj3axNuMHmwRcn5H5+GjoH1glgNQLbPE6Qtuv04SLcvxezcT17cdd9EvFE5ABZnRw30sw21Sd0zUUtd5Kz0oAtdMRqVJiFgVzCYzYJykZFUHm3AyV49Ctq/YRawZVgKkVAaCxwnFvDi6MP6wUfipRPp+zyvwTwax8XdQV5iJ9aEITmf8TsVvin2pv8wB/3Zsf+pmrwrJjMXUZwHv6cNYZfmbRJg5MrjOleh/APrs0B+C6UeFsdt7lZlXlTChmtG7+34EzqjO/oMuFxqopXMjVaJTboB9p+KVnjSTwfEgO0ha3CLT0aJ3xo1Z209P8aFOB/WVJslPTYBAbFiYCQ3z3Fb5VUWN9j8eFU=
  on:
    tags:   true

